#!/usr/bin/env bash

function useage()
{
    cat << EOU
    Useage: bash $0 <path to the binary> <path to the resource path> <package-name>
EOU
exit 1
}

#Validate the inputs
[[ $# < 3 ]] && useage

#Check if the paths are vaild
[[ ! -e $1 ]] && echo "Not a vaild input $1" && exit 1 

poutdir=$(basename $3)
[[ -e $poutdir ]] && echo "destination path $poutdir exists" && exit 1 
poutbindir="$poutdir/bin"
poutlibdir="$poutdir/lib"
mkdir -p $poutbindir
mkdir -p $poutlibdir

#Get the library dependencies
echo "Collecting the shared library dependencies for $1..."
deps=$(ldd $1 | awk 'BEGIN{ORS=" "}$1\
~/^\//{print $1}$3~/^\//{print $3}'\
 | sed 's/,$/\n/')
echo "Copying the dependencies to $poutlibdir"

#Copy the deps
for dep in $deps
do
    echo "Copying $dep"
    cp "$dep" "$poutlibdir"
done
echo "Copying $1"
cp "$1" "$poutbindir"
binname=$(basename $1)
chrpath -r "../lib" "$poutbindir/$binname"
[[ -e $2 ]] && echo "Copying $2" && cp -r "$2" "$poutdir"
echo "tar.gz....."
tar -czf "$3.tar.gz" "$poutdir"

echo "Done!"
